package com.example.onlineresearcher;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class QueryPlanningTest {

    // --- Static helper unit tests ------------------------------------------------------------------

    @Test
    void sanitizeStripsMarkdownAndLatex() {
        assertTrue(ResearchService.sanitizeQuery("**Relation between X and Y**")
                .equals("Relation between X and Y"));
        assertTrue(ResearchService.sanitizeQuery("- `green tea` benefits").equals("green tea benefits"));
        assertTrue(ResearchService.sanitizeQuery("queries:").isEmpty()
                || ResearchService.sanitizeQuery("queries:").equals("queries"));
    }

    @Test
    void isLikelyQueryRejectsHeadersAndSentences() {
        assertTrue(ResearchService.isLikelyQuery("jacobsthal number"));
        assertFalse(ResearchService.isLikelyQuery("queries:"));
        assertFalse(ResearchService.isLikelyQuery(
                "The Jacobsthal function is defined as the smallest positive integer m such that every "
                        + "sequence of m consecutive integers contains an integer coprime to n"));
    }

    @Test
    void deterministicQueriesDecomposeRelationQuestion() {
        List<String> queries = ResearchService.deterministicQueries(
                "Is there any relation between jacobsthal function and jacobsthal number besides their name?");
        assertTrue(queries.contains("jacobsthal function"), queries.toString());
        assertTrue(queries.contains("jacobsthal number"), queries.toString());
        // The shared namesake token is searched too, which surfaces the disambiguation/person page.
        assertTrue(queries.contains("jacobsthal"), queries.toString());
        // None of the decomposed queries should still carry the filler or punctuation.
        assertTrue(queries.stream().noneMatch(q -> q.contains("?")));
        assertTrue(queries.stream().noneMatch(q -> q.toLowerCase().startsWith("is there")));
    }

    @Test
    void commonLeadingWordsFindsSharedNamesake() {
        assertTrue(ResearchService.commonLeadingWords("jacobsthal function", "jacobsthal number")
                .equals("jacobsthal"));
        assertTrue(ResearchService.commonLeadingWords("green tea", "black tea").isEmpty());
    }

    @Test
    void deterministicQueriesHandleVs() {
        List<String> queries = ResearchService.deterministicQueries("green tea vs black tea");
        assertTrue(queries.contains("green tea"), queries.toString());
        assertTrue(queries.contains("black tea"), queries.toString());
    }

    // --- Behavioral regression test: the exact garbage from the real failure log ------------------

    private static class RecordingProvider implements SearchProvider {
        final List<String> received = new ArrayList<>();
        @Override public String name() { return "rec"; }
        @Override public boolean enabled() { return true; }
        @Override public List<WebSearchResult> search(String query, int maxResults) {
            received.add(query);
            return List.of(new WebSearchResult("R", "https://r/" + received.size(), "s"));
        }
    }

    @Test
    void malformedModelQueriesAreCleanedBeforeReachingProviders(@TempDir Path dir) {
        // Reproduce the model output that broke the original run: headers, bold markup, LaTeX, full sentences.
        String garbage = String.join("\n",
                "### Search Queries",
                "**Relation between Jacobsthal function and Jacobsthal numbers**",
                "The Jacobsthal function, denoted as \\( j(n) \\), is defined as the smallest positive integer "
                        + "\\( m \\) such that every sequence of consecutive integers contains an integer coprime.",
                "Jacobsthal numbers are a sequence of integers that can be generated by the recurrence relation:");

        ChatModel model = (messages, maxTokens, temperature) -> {
            String system = messages.stream().filter(m -> m.role().equals("system"))
                    .map(Message::content).findFirst().orElse("");
            if (system.contains("decide whether a user's request")) return "CLEAR";
            if (system.contains("web search engine queries")) return garbage;
            if (system.contains("judge whether the gathered")) return "SUFFICIENT";
            if (system.contains("careful research assistant")) return "ANSWER";
            return "";
        };
        RecordingProvider provider = new RecordingProvider();
        SkillStore store = new SkillStore(dir.toString());
        WebResearchService web = new WebResearchService(List.of(provider));
        ResearchSkillService skillService = new ResearchSkillService(store, web, model);
        // Pre-build + version-stamp the skill via an empty web so the bootstrap search doesn't reach the
        // recording provider and the only queries it sees come from the actual research turn.
        new ResearchSkillService(store, new WebResearchService(List.of()), model).ensureResearchSkill();
        ResearchService service = new ResearchService(
                new ConversationMemory(new TokenEstimator(4), (p, m) -> "", 8100),
                model, web, skillService, new SportsScoreSkillService(store),
                new FailToFindSkillService(store), 256, 8, 1, 16000, 5, 3);

        service.handle("Is there any relation between jacobsthal function and jacobsthal number besides their name?");

        assertFalse(provider.received.isEmpty(), "the provider should have been queried");
        for (String q : provider.received) {
            assertFalse(q.startsWith("#"), "no markdown header reached the provider: " + q);
            assertFalse(q.contains("**"), "no bold markup reached the provider: " + q);
            assertFalse(q.contains("\\("), "no LaTeX reached the provider: " + q);
            assertTrue(q.split("\\s+").length <= 12, "no full-sentence query reached the provider: " + q);
        }
        // The decomposed entity queries must be among those searched.
        assertTrue(provider.received.contains("jacobsthal function"), provider.received.toString());
        assertTrue(provider.received.contains("jacobsthal number"), provider.received.toString());
    }
}
